### PR TITLE
Getting Refinements up and running

### PR DESCRIPTION
**Pull request by mariari**
Things that need to get done before we merge this PR

- [ ] Get a demo of this used on the Frontend ML --> Lisp Translation
- [ ] Figure out the trouble points
- [ ] Learn how to use Liquid more

### CODE REVIEW

**Comment by mariari** [comment]
Tries to implement #765

**Comment by cyberglot** [comment]
I think we might have uncovered a bug in liquid haskell, I will report back soon.

**Comment by cyberglot** [comment]
I just had to remove termination and totality checks that it compiles normally now.

**Comment by mariari** [comment]
Some other issues to look out for
```haskell
import Juvix.Library (IO)
```
this type of import is dangerous as it tries to hardwire proofs so we have to import all of our library

**Comment by mariari** [comment]
Seems `Juvix.ToCore.Types.Errors` takes forever to compile with liquid, we'll likely want a flag to have it ignore such large adts... probably a max depth option

**Pull request closed without merging**
